# Generated by Django 3.2.5 on 2021-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_age', models.FloatField()),
                ('survey_gender', models.CharField(max_length=15)),
            ],
        ),
    ]
