# Generated by Django 3.2.5 on 2021-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='survey_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='survey_gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
