# Generated by Django 3.2.5 on 2021-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_viewer_survey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='survey_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
