# Generated by Django 3.2.5 on 2021-08-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_viewer_survey_name'),
        ('collector', '0003_auto_20210812_0859'),
    ]

    operations = [
    ]
